# Generated by Django 3.1.2 on 2021-01-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruduser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='user',
        ),
    ]
